[project]
name = "ada-conversations-api-demo"
version = "0.0.1"
description = "A demo of the Ada Conversations API"
authors = [{ name = "Ada", email = "developer-partnerships@ada.support" }]
readme = "README.md"
requires-python = ">= 3.12"
dependencies = ["requests >= 2.32.3"]
